repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: "22.10.0"
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8.git
    rev: "5.0.4"
    hooks:
    -   id: flake8
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        stages: [commit]
        types: [python]
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true

    -   id: requirements-updater
        name: requirements-updater
        stages: [commit]
        entry: backend/app/hooks/update-requirements.sh
        language: system
        always_run: true
