"""group revision

Revision ID: 294922faaee8
Revises: b813e1296189
Create Date: 2022-12-02 20:08:29.083075

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '294922faaee8'
down_revision = 'b813e1296189'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False))
    op.add_column('group', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'description')
    op.drop_column('group', 'name')
    # ### end Alembic commands ###
