"""add tasks

Revision ID: e327585690ab
Revises: 66927367b62d
Create Date: 2022-11-18 19:12:54.096524

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e327585690ab'
down_revision = '66927367b62d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
